export { default as NavBar } from "./NavBar/NavBar";
export { default as Bottom  } from "./Bottom/Bottom";
export { default as LoginForm } from "./LoginForm/LoginForm";
export { default as LoginGallery } from "./LoginGallery/LoginGallery";
export { default as RegisterForm } from "./RegisterForm/RegisterForm";
export { default as RegisterGallery } from "./RegisterGallery/RegisterGallery";
export { default as Loading } from "./Loading/Loading";
export { default as StateProvider } from "./StateProvider/StateProvider";
export { default as Benefit } from "./Benefit/Benefit";
export { default as ServicesList } from "./ServicesList/ServicesList";
export { default as ServicesGroup } from "./ServicesGroup/ServicesGroup";
export { default as HomeHero } from "./HomeHero/HomeHero";
export { default as DefaultHero } from "./DefaultHero/DefaultHero";
export { default as DailyStatus } from "./DailyStatus/DailyStatus";
export { default as IntroBlog } from "./IntroBlog/IntroBlog";
export { default as IntroBlogRight } from "./IntroBlogRight/IntroBlogRight";
export { default as VideoPlace } from "./VideoPlace/VideoPlace";
export { default as GalleryHome } from "./GalleryHome/GalleryHome";
export { default as SkeletonServicesList } from "./SkeletonServicesList/SkeletonServicesList";
export { default as BookingGroup } from "./BookingGroup/BookingGroup";
export { default as PopularBlogs } from "./PopularBlogs/PopularBlogs";
export { default as NormalBlogs } from "./NormalBlogs/NormalBlogs";
export { default as BlogContent } from "./BlogContent/BlogContent";
export { default as ServiceDetailGallery } from "./ServiceDetailGallery/ServiceDetailGallery";
export { default as PopularDestination } from "./PopularDestination/PopularDestination";
export { default as ForgotPasswordForm } from "./ForgotPasswordForm/ForgotPasswordForm";
export { default as SuccessChecking } from "./SuccessCheking/SuccessChecking";
export { default as ResetPasswordForm } from "./ResetPasswordForm/ResetPasswordForm";
export { default as ServiceStepper } from "./ServiceStepper/ServiceStepper";
export { default as ServiceReview } from "./ServiceReview/ServiceReview";
export { default as FloatingChat } from "./FloatingChat/FloatingChat";
export { default as ServiceSummary } from "./ServiceSummary/ServiceSummary";
export { default as ServiceOverview } from "./ServiceOverview/ServiceOverview";
export { default as BlogContentTable} from "./BlogContentTable/BlogContentTable";
export { default as BlogContentRight} from "./BlogContentRight/BlogContentRight";
export { default as BlogContentRelated} from "./BlogContentRelated/BlogContentRelated";
export { default as BlogContentComment } from "./BlogContentComment/BlogContentComment";
export { default as Skeleton } from "./Skeleton/Skeleton";
export { default as BlogList } from "./BlogList/BlogList";
export { default as ThemeRegistry } from "./ThemeRegistry/ThemeRegistry";
// //

export { default as AdminNavBar } from "./AdminNavBar/AdminNavBar";
export { default as AdminHotel } from "./AdminHotel/AdminHotel";
export { default as TermAndCondition } from "./TermAndCondition/TermAndCondition";
