import './global.scss';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ToastContainer } from 'react-toastify';

import 'react-toastify/dist/ReactToastify.css';
import { StateProvider, ThemeRegistry } from '../_components';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'VN Travel',
  description: 'Generated by development team',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeRegistry options={{ key: 'mui' }}>
          <ToastContainer position='bottom-left'/>
            <StateProvider>
              { children }
            </StateProvider>
        </ThemeRegistry>
      </body>
    </html>
  )
}
