import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Provider from '../_context/Provider'
import '../_assets/globalStyles.scss'



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Travel website',
  description: 'Generated by development team',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  )
}
